### ISSUE TITLE
Support custom actions that apply to all instances of a given resource

### ISSUE THREAD

**Issue by craigedmunds** [flyvictor/fortune#123] opened 2015-03-06 13:37 UTC
Fortune actions allow us to restrict the scope of a resource by filtering, or to allow RPC style methods to be added to resources, where a use case doesn't naturally fit into a resourceful interaction, e.g. /users/:id/send-password-reset-email. A test covering this feature is [here](https://github.com/flyvictor/fortune/blob/master/test/fortune/actions.js)

Our initial implementation allowed actions to be added to an individual resource, identified by ID, i.e. /users/:id/action-name

We also want to allow actions to apply to the resource at a top level, to allow filtering. [The example](https://github.com/flyvictor/fortune/blob/master/test/fortune/actions.js) shows how we'd like to be able to filter the users collection by a field that identifies admin users, such that the URL /users/admin-users returns only admin users.

It should also be possible to further filter this list, or support other fortune semantics like sorting, paging, including, etc, e.g. /users/admin-users?include=addresses&filter[firstName]=Craig&sort=lastName&page=1&pageSize=2

**Comment by EugeneKostrikov** [comment] 2015-03-06 13:46
What are pros / cons of the following syntax options: 
* ANY /:resource/:action-name
* POST /:resource/:action-name
* ANY /:resource/filter/:action-name
* ANY /:resource/action/:action-name

Which one will be most suitable here and why? Is there any better option?

**Comment by stoykostanchev** [comment] 2015-12-03 10:50
Possible duplicate of https://github.com/flyvictor/fortune/pull/153

**Closed by stoykostanchev** 2015-12-03 10:50 UTC
Labels: Medium Complex
